name: Test and Build Nightly

on:
  - push
  - pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build Nightly for ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: nevermore-fms
            asset_name: nevermore-fms-linux-amd64
          - os: windows-latest
            artifact_name: nevermore-fms.exe
            asset_name: nevermore-fms-windows-amd64.exe
          - os: macos-latest
            artifact_name: nevermore-fms
            asset_name: nevermore-fms-osx-amd64
            
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Install Deps
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt install libwebkit2gtk-4.0-dev libappindicator3-dev clang libgtksourceview-3.0-dev
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test --verbose
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.asset_name }}
        path: target/debug/${{ matrix.artifact_name }}
